python main.py \
  --batchsize 128 \
  --epoch 80 \
  --lr 0.0001 \
  --enable_lat 'True' \
  --test_flag 'False' \
  --train_data_path "/media/dsg3/dsgprivate/lat/data/sampled_imagenet/" \
  --model_path "/media/dsg3/dsgprivate/yuhang/model/resnet18/lat_p5e0.3a0.7/" \
  --pro_num 5 \
  --alpha 0.7 \
  --epsilon 0.3 \
  --dataset "imagenet" \
  --model "resnet" \
  --dropout 'True' \
  --test_data_path "/media/dsg3/dsgprivate/lat/test/new/test_data_cln.p" \
  --test_label_path "/media/dsg3/dsgprivate/lat/test/new/test_label.p" \
  --logfile 'log_p5e0.3a0.7_5.txt' 
